### ISSUE TITLE
hello , help ~ about ` token `

### ISSUE THREAD

**Issue by arleyGuoLei** [fjc0k/weixiao.js#1]
```js
const wx = new Weixiao({
  key: 'your key',
  secret: 'your secret',
  token: 'your token' // 仅 "消息回复类" 应用需要 token
});
```

hello,boy .  Where is the `token` application?   -> in  https://open.weixin.qq.com/  ???

**Comment by fjc0k** [comment]
https://open.weixiao.qq.com/app/index.html#/api?content=open&_k=yzjzql

![image](https://user-images.githubusercontent.com/13151189/51589618-80b1dd00-1f22-11e9-9c51-fb5777bafe9f.png)

**Comment by arleyGuoLei** [comment]
oh, thinks ,  but I've already seen the document , I have a question is the token in the picture?
![image](https://user-images.githubusercontent.com/40717741/51589781-f5851700-1f22-11e9-9501-e8f7fa91dc6b.png)



-----

在腾讯微校上的应用, 应该是面向所有公众号的吧?  如果只是放我这个token  那有用吗?

还是主要看的是我代码里自己自定义的那个token

**Comment by fjc0k** [comment]
就是你代码里的 token。

**Comment by arleyGuoLei** [comment]
oh,  i try try...  thinks.
